[tool.poetry]
name = "foghorn-irc"
version = "0.1.0"
description = "A quasi-compliant IRCv3 server written off Modern IRC."
authors = ["Elias Gabriel <me@eliasfgabriel.com>"]
license = "AGPL-3.0"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
black = "^21.5b1"
irc-parser-tests = "^0.0.4"
pytest = "^6.2.4"
flake8 = "^3.9.2"
isort = "^5.8.0"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
