name: CI

on: [push, pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Lint Dockerfile
              uses: brpaz/hadolint-action@master
              with:
                  dockerfile: "Dockerfile"
            - name: Check formatting
              uses: psf/black@stable

    test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: [3.7, 3.8, 3.9, pypy-3.7]
        env:
            POETRY_CACHE_DIR: ~/.cache/pypoetry
            PIP_CACHE_DIR: ~/.cache/pip
        name: ${{ matrix.python-version }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - uses: actions/cache@v2
              id: cache-deps
              with:
                  path: |
                      ${{ env.POETRY_CACHE_DIR }}
                      ${{ env.PIP_CACHE_DIR }}
                      .venv
                  key: ${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}
            - name: Install dependencies
              if: steps.cache-deps.outputs.cache-hit != 'true'
              run: |
                  python -m pip install --upgrade pip --cache-dir ${{ env.PIP_CACHE_DIR }}
                  pip install poetry --cache-dir ${{ env.PIP_CACHE_DIR }}
                  poetry install --remove-untracked --no-ansi --no-interaction
            - name: Test with pytest
              run: poetry run pytest -vv tests
