name: CI

on: [push, pull_request]

jobs:
  dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: "Dockerfile"

  python:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, pypy-3.7]
    env:
      POETRY_CACHE_DIR: ~/.cache/poetry
      MYPY_CACHE_DIR: ~/.cache/mypy
    name: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.1.2
      - uses: actions/cache@v2
        id: cache-deps
        with:
          path: |
            ${{ env.MYPY_CACHE_DIR }}
            ${{ env.POETRY_CACHE_DIR }}
            .venv
          key: ${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: poetry install --remove-untracked --no-ansi --no-interaction
      - name: Check formatting
        run: poetry run black --check --diff .
      - name: Check typing
        run: |
          mkdir -p ${{ env.MYPY_CACHE_DIR }}
          poetry run mypy --install-types
          poetry run mypy --pretty .
      - name: Check test assertions
        run: poetry run pytest -vv tests
